### ISSUE TITLE
1d input of a LayeredModel from EvalModel

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/easi#28]
Hi,
I would like to define the 1d input of a LayeredModel with an EvalModel combining 2 inputs (in the real-case application, one input will be from an ASAGI component). This does not work. Do you think is it a limitation of the component or a bug?

Thanks,

Thomas.

test.yaml
```
!Switch
[plastCo]: !LayeredModel
      map: !Include test2.yaml
      interpolation: linear
      parameters: [plastCo]
      nodes:
        10e3:  [222339.89064034278]
        -10e3: [354563.38402222196]
```
test2.yaml
```
!EvalModel
parameters: [elevation,z]
model: !Switch
  [elevation]: !ConstantMap
    map: 
        elevation: 10.
  [z]: !AffineMap
    matrix:
      z: [0.0, 0.0, 1.0]
    translation:
      z: 0.0
components: !FunctionMap
    map:
      z_below_surface: |
        return elevation + z;
```
Error message:
```
di73yeq4@login03:/hppfs/work/pr63qo/di73yeq4/SulawesiSetupNewYann> easicube '{from: [0,0,150], to: [1,1,250], N: [1,1,10], group: 1}' test.yaml 
test.yaml: yaml-cpp: error at line 2, column 12: Layered model requires 1D input (got elevation,z).
!<!LayeredModel>
map: !<!Include> test2.yaml
interpolation: linear
parameters: [plastCo]
nodes:
  10e3: [222339.89064034278]
  -10e3: [354563.38402222196]
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error while parsing easi model file.
Aborted (core dumped)
```
