### ISSUE TITLE
EvalModel with more than 8 parameters

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/easi#5]
If I used this file:
``` yaml
!EvalModel
parameters: [test, lithostaticStress, b_xx, b_yy, b_xy, b_yz, b_xz, gamma]
model: !Switch
  [test]: !AffineMap
      matrix:
        z: [0.0, 0.0, 1.0]
      translation:
        z: 0
      components:
        - !FunctionMap
          map:
           test: return z;
  [lithostaticStress, b_xx, b_yy, b_zz, b_xy, b_yz, b_xz,gamma,Omega]: !ConstantMap
          map:
              lithostaticStress: 0.974
              b_xx: 0.974
              b_yy: 0.974
              b_zz: 0.974
              b_xy: 0.974
              b_yz: 0.974
              b_xz: 0.974
              gamma: 0.974
components: !FunctionMap
      map:
        s_zz:     return lithostaticStress;
        s_xx:     return lithostaticStress;
        s_yy:     return lithostaticStress;
        s_xy:     return lithostaticStress;
        s_yz:     return lithostaticStress;
        s_xz:     return lithostaticStress;
        bulkFriction: |
          return test;
        plastCo: |
          return test;
```
And plot bulkFriction against z, I get, as expected:
```
z bulkFriction
-100  -100
-200  -200
-300  -300
-400  -400
```
Now same file, with one more parameter:

``` yaml
!EvalModel
parameters: [test, lithostaticStress, b_xx, b_yy, b_xy, b_yz, b_xz, gamma, Omega]
model: !Switch
  [test]: !AffineMap
      matrix:
        z: [0.0, 0.0, 1.0]
      translation:
        z: 0
      components:
        - !FunctionMap
          map:
           test: return z;
  [lithostaticStress, b_xx, b_yy, b_zz, b_xy, b_yz, b_xz,gamma,Omega]: !ConstantMap
          map:
              lithostaticStress: 0.974
              b_xx: 0.974
              b_yy: 0.974
              b_zz: 0.974
              b_xy: 0.974
              b_yz: 0.974
              b_xz: 0.974
              gamma: 0.974
              Omega: 0.974
components: !FunctionMap
      map:
        s_zz:     return lithostaticStress;
        s_xx:     return lithostaticStress;
        s_yy:     return lithostaticStress;
        s_xy:     return lithostaticStress;
        s_yz:     return lithostaticStress;
        s_xz:     return lithostaticStress;
        bulkFriction: |
          return test;
        plastCo: |
          return test;
```
and I get:
```
-100 2.16654e-317
-200 2.16654e-317
-300 2.16654e-317
-400 2.16654e-317
```
