### ISSUE TITLE
Could not find model for point with AffineMap + ASAGI

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/easi#7]
Hi,

I m asking for some model parameters (s_ij) at 0,0,0 and got the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  fault2.yaml@2: Could not find model for point [ 348441 4.76021e+06 0 ] in group 1.
```
here is the yaml file:
```
!Switch
[s_zz,s_yy,s_yz,s_xx,s_xz,s_xy,d_c,mu_s]: !AffineMap
  matrix:
    #strike 155
    #dip 47
    xf: [0.4054811 , -0.91410343,  0.   ]
    yf: [-0.62424723, -0.2769057 ,  0.73050574]
    zf: [-0.6677578 , -0.29620627, -0.68290656]
  translation:
    xf: 348441.377459
    yf: 4760209.93637
    zf: 0.0
  components: !ASAGI
          file: norciax_210fault_nncia.nc
          parameters: [s_zz,s_yy,s_yz,s_xx,s_xz,s_xy,d_c,mu_s]
          var: data
          interpolation: nearest
[mu_d, cohesion, forced_rupture_time]: !ConstantMap
  map:
     mu_d:        0.2
     cohesion:    0.0
     forced_rupture_time: 1e10
```
If I use instead:
```
!Switch
[s_zz,s_yy,s_yz,s_xx,s_xz,s_xy,d_c,mu_s]: !ASAGI
          file: norciax_210fault_nncia.nc
          parameters: [s_zz,s_yy,s_yz,s_xx,s_xz,s_xy,d_c,mu_s]
          var: data
          interpolation: nearest
[mu_d, cohesion, forced_rupture_time]: !ConstantMap
  map:
     mu_d:        0.2
     cohesion:    0.0
     forced_rupture_time: 1e10
```
I don't get an error and I m able to recover the stress values.
```
../EvaluateVpVs/EvaluateSij fault4.yaml 0 0 0
-9.70886e+06 -1.79305e+07 -5.23607e+07 -1.62028e+07 3.24235e+07 2.37379e+07
```
If the coordinates are out of range of the netcdf file, I get as expected:
```
../EvaluateVpVs/EvaluateSij fault4.yaml 0 0 1e6
Thu Jan 09 14:32:22, Warn:  ASAGI: Coordinate in dimension 2  is out of range. Fixing. 
-3.1084e+07 -5.82616e+07 -1.69259e+08 -5.24857e+07 1.05171e+08 7.64816e+07
```

Therefore I think there is a bug in easi.

Thomas.
